## Project
#### Author: Zhili Zhang - Net ID: zz2382

In [1]:
import numpy as np
import numpy.random as random
import itertools
import warnings
from math import exp
from model import Model
warnings.filterwarnings('ignore')

In [2]:
# Input Data X
X = [[1,1], [1,-1], [-1,1], [-1,-1]]

# Input target Y
Y = [-1,1,1,-1]

X = np.array(X)
Y = np.array(Y)

In [3]:
w01 = np.array([[-0.3378,0.2771,0.2859,-0.3329],
                [0.1970,0.3191,-0.1448,0.3594],
                [0.3099,0.1904,-0.0347,-0.4861]])
w12 = np.array([[-0.1401], [0.4919], [-0.2913], \
                [-0.3979], [0.3581]])

In [4]:
print(w01.shape)
print(w12.shape)

(3, 4)
(5, 1)


### Experiment with quadratic cost function

In [5]:
model = Model(N0=2, N1=4, N2=1, x0=1.0, lr=0.2, tol=0.05, \
              zeta=1, epoch_thres=5000, cost='L2', transfer='tansig')

Model setup:
Network: 2-4-1
x0: 1.0; learning rate: 0.2; Tolerance: 0.05;
zeta: 1; maximum running epochs: 5000;
Cost function: L2; transfer function: tansig


In [6]:
# put in the preset weights, train for 1 epoch
model.train(X, Y, epochs=1, input_weights=True, w01=w01, w12=w12)

Epoch: 1; square error: 2.2187


In [7]:
print(model.predict(X))
print(model.stop_epoch)
print(model.w01)
print(model.w12)

[[-0.11691667]
 [-0.0883645 ]
 [-0.20013562]
 [-0.17436637]]
1
[[-0.32243413  0.26504268  0.27330512 -0.32503622]
 [ 0.19347555  0.31675476 -0.144748    0.36374521]
 [ 0.30686735  0.18845288 -0.03301594 -0.48859019]]
[[-0.08027444]
 [ 0.47534885]
 [-0.27642811]
 [-0.38395025]
 [ 0.34801327]]


In [8]:
# put in the preset weights, 
# train until converge or reach the epoch threshold
model.train(X, Y, epochs=-1, input_weights=True, w01=w01, w12=w12)

Epoch: 1; square error: 2.2187
Epoch: 2; square error: 2.1980
Epoch: 3; square error: 2.1840
Epoch: 4; square error: 2.1744
Epoch: 5; square error: 2.1678
Epoch: 6; square error: 2.1630
Epoch: 7; square error: 2.1594
Epoch: 8; square error: 2.1567
Epoch: 9; square error: 2.1546
Epoch: 10; square error: 2.1528
Epoch: 11; square error: 2.1512
Epoch: 12; square error: 2.1499
Epoch: 13; square error: 2.1487
Epoch: 14; square error: 2.1476
Epoch: 15; square error: 2.1466
Epoch: 16; square error: 2.1456
Epoch: 17; square error: 2.1447
Epoch: 18; square error: 2.1438
Epoch: 19; square error: 2.1430
Epoch: 20; square error: 2.1422
Epoch: 21; square error: 2.1414
Epoch: 22; square error: 2.1407
Epoch: 23; square error: 2.1400
Epoch: 24; square error: 2.1393
Epoch: 25; square error: 2.1387
Epoch: 26; square error: 2.1381
Epoch: 27; square error: 2.1375
Epoch: 28; square error: 2.1369
Epoch: 29; square error: 2.1363
Epoch: 30; square error: 2.1358
Epoch: 31; square error: 2.1352
Epoch: 32; square

Epoch: 265; square error: 0.0654
Epoch: 266; square error: 0.0647
Epoch: 267; square error: 0.0639
Epoch: 268; square error: 0.0631
Epoch: 269; square error: 0.0624
Epoch: 270; square error: 0.0616
Epoch: 271; square error: 0.0609
Epoch: 272; square error: 0.0602
Epoch: 273; square error: 0.0595
Epoch: 274; square error: 0.0589
Epoch: 275; square error: 0.0582
Epoch: 276; square error: 0.0576
Epoch: 277; square error: 0.0569
Epoch: 278; square error: 0.0563
Epoch: 279; square error: 0.0557
Epoch: 280; square error: 0.0551
Epoch: 281; square error: 0.0546
Epoch: 282; square error: 0.0540
Epoch: 283; square error: 0.0534
Epoch: 284; square error: 0.0529
Epoch: 285; square error: 0.0523
Epoch: 286; square error: 0.0518
Epoch: 287; square error: 0.0513
Epoch: 288; square error: 0.0508
Epoch: 289; square error: 0.0503
Epoch: 290; square error: 0.0498


In [9]:
print(model.predict(X))
print(model.stop_epoch)
print(model.w01)
print(model.w12)

[[-0.86701634]
 [ 0.82900739]
 [ 0.82057987]
 [-0.86486827]]
290
[[-1.83399183 -0.25728563  0.17439781 -2.64740313]
 [-2.19263493  0.46144964 -0.03467615  2.82319611]
 [ 2.23930843 -0.27385074  0.03224229 -2.79902048]]
[[ 2.651425  ]
 [ 3.28042316]
 [-0.59893465]
 [ 0.14726765]
 [ 3.4546775 ]]


In [10]:
# randomize the weights with zeta
model.train(X, Y, epochs=-1, input_weights=False)

Epoch: 1; square error: 2.6503
Epoch: 2; square error: 2.5343
Epoch: 3; square error: 2.4475
Epoch: 4; square error: 2.3860
Epoch: 5; square error: 2.3426
Epoch: 6; square error: 2.3107
Epoch: 7; square error: 2.2860
Epoch: 8; square error: 2.2656
Epoch: 9; square error: 2.2480
Epoch: 10; square error: 2.2323
Epoch: 11; square error: 2.2178
Epoch: 12; square error: 2.2043
Epoch: 13; square error: 2.1914
Epoch: 14; square error: 2.1789
Epoch: 15; square error: 2.1666
Epoch: 16; square error: 2.1545
Epoch: 17; square error: 2.1424
Epoch: 18; square error: 2.1301
Epoch: 19; square error: 2.1176
Epoch: 20; square error: 2.1047
Epoch: 21; square error: 2.0914
Epoch: 22; square error: 2.0776
Epoch: 23; square error: 2.0632
Epoch: 24; square error: 2.0481
Epoch: 25; square error: 2.0322
Epoch: 26; square error: 2.0154
Epoch: 27; square error: 1.9977
Epoch: 28; square error: 1.9790
Epoch: 29; square error: 1.9592
Epoch: 30; square error: 1.9383
Epoch: 31; square error: 1.9161
Epoch: 32; square

In [11]:
print(model.predict(X))
print(model.stop_epoch)
print(model.w01)
print(model.w12)

[[-0.8339582 ]
 [ 0.82530257]
 [ 0.83684978]
 [-0.89055612]]
164
[[ 0.11541273 -2.41826226  1.85908646 -1.38107329]
 [ 0.40304981 -2.73780352 -1.98330098 -1.03339741]
 [ 0.18151859  2.40767087  2.4306813  -0.80371965]]
[[ 2.03783474]
 [-0.07782772]
 [ 3.36190686]
 [-3.26933905]
 [-1.32243829]]


### Experiment with Cross Entropy cost function

In [12]:
model = Model(N0=2, N1=4, N2=1, x0=1.0, lr=0.2, tol=0.05, \
              zeta=1, epoch_thres=5000, cost='BCE', transfer='tansig')

Model setup:
Network: 2-4-1
x0: 1.0; learning rate: 0.2; Tolerance: 0.05;
zeta: 1; maximum running epochs: 5000;
Cost function: BCE; transfer function: tansig


In [13]:
# put in the preset weights, train for 1 epoch
model.train(X, Y, epochs=1, input_weights=True, w01=w01, w12=w12)

Epoch: 1; square error: 2.3981


In [14]:
print(model.predict(X))
print(model.stop_epoch)
print(model.w01)
print(model.w12)

[[-0.07374902]
 [-0.04603113]
 [-0.15704627]
 [-0.13204053]]
1
[[-0.30754551  0.24693804  0.25732658 -0.30887916]
 [ 0.19383967  0.30895515 -0.14727152  0.36911844]
 [ 0.29881712  0.18811518 -0.02889164 -0.48928638]]
[[-0.01923564]
 [ 0.44724602]
 [-0.24360234]
 [-0.35686098]
 [ 0.32501904]]


In [15]:
# put in the preset weights, 
# train until converge or reach the epoch threshold
model.train(X, Y, epochs=-1, input_weights=True, w01=w01, w12=w12)

Epoch: 1; square error: 2.3981
Epoch: 2; square error: 2.3506
Epoch: 3; square error: 2.3277
Epoch: 4; square error: 2.3143
Epoch: 5; square error: 2.3050
Epoch: 6; square error: 2.2978
Epoch: 7; square error: 2.2917
Epoch: 8; square error: 2.2865
Epoch: 9; square error: 2.2820
Epoch: 10; square error: 2.2779
Epoch: 11; square error: 2.2743
Epoch: 12; square error: 2.2711
Epoch: 13; square error: 2.2681
Epoch: 14; square error: 2.2655
Epoch: 15; square error: 2.2631
Epoch: 16; square error: 2.2608
Epoch: 17; square error: 2.2588
Epoch: 18; square error: 2.2570
Epoch: 19; square error: 2.2552
Epoch: 20; square error: 2.2536
Epoch: 21; square error: 2.2522
Epoch: 22; square error: 2.2508
Epoch: 23; square error: 2.2495
Epoch: 24; square error: 2.2482
Epoch: 25; square error: 2.2471
Epoch: 26; square error: 2.2460
Epoch: 27; square error: 2.2449
Epoch: 28; square error: 2.2439
Epoch: 29; square error: 2.2430
Epoch: 30; square error: 2.2420
Epoch: 31; square error: 2.2411
Epoch: 32; square

Epoch: 298; square error: 2.2091
Epoch: 299; square error: 2.2091
Epoch: 300; square error: 2.2091
Epoch: 301; square error: 2.2091
Epoch: 302; square error: 2.2091
Epoch: 303; square error: 2.2091
Epoch: 304; square error: 2.2091
Epoch: 305; square error: 2.2091
Epoch: 306; square error: 2.2091
Epoch: 307; square error: 2.2091
Epoch: 308; square error: 2.2091
Epoch: 309; square error: 2.2091
Epoch: 310; square error: 2.2091
Epoch: 311; square error: 2.2091
Epoch: 312; square error: 2.2091
Epoch: 313; square error: 2.2091
Epoch: 314; square error: 2.2091
Epoch: 315; square error: 2.2091
Epoch: 316; square error: 2.2091
Epoch: 317; square error: 2.2091
Epoch: 318; square error: 2.2091
Epoch: 319; square error: 2.2091
Epoch: 320; square error: 2.2091
Epoch: 321; square error: 2.2091
Epoch: 322; square error: 2.2091
Epoch: 323; square error: 2.2091
Epoch: 324; square error: 2.2091
Epoch: 325; square error: 2.2091
Epoch: 326; square error: 2.2091
Epoch: 327; square error: 2.2091
Epoch: 328

Epoch: 698; square error: 2.2091
Epoch: 699; square error: 2.2091
Epoch: 700; square error: 2.2091
Epoch: 701; square error: 2.2091
Epoch: 702; square error: 2.2091
Epoch: 703; square error: 2.2091
Epoch: 704; square error: 2.2091
Epoch: 705; square error: 2.2091
Epoch: 706; square error: 2.2091
Epoch: 707; square error: 2.2091
Epoch: 708; square error: 2.2091
Epoch: 709; square error: 2.2091
Epoch: 710; square error: 2.2091
Epoch: 711; square error: 2.2091
Epoch: 712; square error: 2.2091
Epoch: 713; square error: 2.2091
Epoch: 714; square error: 2.2091
Epoch: 715; square error: 2.2091
Epoch: 716; square error: 2.2091
Epoch: 717; square error: 2.2091
Epoch: 718; square error: 2.2091
Epoch: 719; square error: 2.2091
Epoch: 720; square error: 2.2091
Epoch: 721; square error: 2.2091
Epoch: 722; square error: 2.2091
Epoch: 723; square error: 2.2091
Epoch: 724; square error: 2.2091
Epoch: 725; square error: 2.2091
Epoch: 726; square error: 2.2091
Epoch: 727; square error: 2.2091
Epoch: 728

Epoch: 1096; square error: 2.2091
Epoch: 1097; square error: 2.2091
Epoch: 1098; square error: 2.2091
Epoch: 1099; square error: 2.2091
Epoch: 1100; square error: 2.2091
Epoch: 1101; square error: 2.2091
Epoch: 1102; square error: 2.2091
Epoch: 1103; square error: 2.2091
Epoch: 1104; square error: 2.2091
Epoch: 1105; square error: 2.2091
Epoch: 1106; square error: 2.2091
Epoch: 1107; square error: 2.2091
Epoch: 1108; square error: 2.2091
Epoch: 1109; square error: 2.2091
Epoch: 1110; square error: 2.2091
Epoch: 1111; square error: 2.2091
Epoch: 1112; square error: 2.2091
Epoch: 1113; square error: 2.2091
Epoch: 1114; square error: 2.2091
Epoch: 1115; square error: 2.2091
Epoch: 1116; square error: 2.2091
Epoch: 1117; square error: 2.2091
Epoch: 1118; square error: 2.2091
Epoch: 1119; square error: 2.2091
Epoch: 1120; square error: 2.2091
Epoch: 1121; square error: 2.2091
Epoch: 1122; square error: 2.2091
Epoch: 1123; square error: 2.2091
Epoch: 1124; square error: 2.2091
Epoch: 1125; s

Epoch: 1380; square error: 2.2091
Epoch: 1381; square error: 2.2091
Epoch: 1382; square error: 2.2091
Epoch: 1383; square error: 2.2091
Epoch: 1384; square error: 2.2091
Epoch: 1385; square error: 2.2091
Epoch: 1386; square error: 2.2091
Epoch: 1387; square error: 2.2091
Epoch: 1388; square error: 2.2091
Epoch: 1389; square error: 2.2091
Epoch: 1390; square error: 2.2091
Epoch: 1391; square error: 2.2091
Epoch: 1392; square error: 2.2091
Epoch: 1393; square error: 2.2091
Epoch: 1394; square error: 2.2091
Epoch: 1395; square error: 2.2091
Epoch: 1396; square error: 2.2091
Epoch: 1397; square error: 2.2091
Epoch: 1398; square error: 2.2091
Epoch: 1399; square error: 2.2091
Epoch: 1400; square error: 2.2091
Epoch: 1401; square error: 2.2091
Epoch: 1402; square error: 2.2091
Epoch: 1403; square error: 2.2091
Epoch: 1404; square error: 2.2091
Epoch: 1405; square error: 2.2091
Epoch: 1406; square error: 2.2091
Epoch: 1407; square error: 2.2091
Epoch: 1408; square error: 2.2091
Epoch: 1409; s

Epoch: 1652; square error: 2.2091
Epoch: 1653; square error: 2.2091
Epoch: 1654; square error: 2.2091
Epoch: 1655; square error: 2.2091
Epoch: 1656; square error: 2.2091
Epoch: 1657; square error: 2.2091
Epoch: 1658; square error: 2.2091
Epoch: 1659; square error: 2.2091
Epoch: 1660; square error: 2.2091
Epoch: 1661; square error: 2.2091
Epoch: 1662; square error: 2.2091
Epoch: 1663; square error: 2.2091
Epoch: 1664; square error: 2.2091
Epoch: 1665; square error: 2.2091
Epoch: 1666; square error: 2.2091
Epoch: 1667; square error: 2.2091
Epoch: 1668; square error: 2.2091
Epoch: 1669; square error: 2.2091
Epoch: 1670; square error: 2.2091
Epoch: 1671; square error: 2.2091
Epoch: 1672; square error: 2.2091
Epoch: 1673; square error: 2.2091
Epoch: 1674; square error: 2.2091
Epoch: 1675; square error: 2.2091
Epoch: 1676; square error: 2.2091
Epoch: 1677; square error: 2.2091
Epoch: 1678; square error: 2.2091
Epoch: 1679; square error: 2.2091
Epoch: 1680; square error: 2.2091
Epoch: 1681; s

Epoch: 1912; square error: 2.2091
Epoch: 1913; square error: 2.2091
Epoch: 1914; square error: 2.2091
Epoch: 1915; square error: 2.2091
Epoch: 1916; square error: 2.2091
Epoch: 1917; square error: 2.2091
Epoch: 1918; square error: 2.2091
Epoch: 1919; square error: 2.2091
Epoch: 1920; square error: 2.2091
Epoch: 1921; square error: 2.2091
Epoch: 1922; square error: 2.2091
Epoch: 1923; square error: 2.2091
Epoch: 1924; square error: 2.2091
Epoch: 1925; square error: 2.2091
Epoch: 1926; square error: 2.2091
Epoch: 1927; square error: 2.2091
Epoch: 1928; square error: 2.2091
Epoch: 1929; square error: 2.2091
Epoch: 1930; square error: 2.2091
Epoch: 1931; square error: 2.2091
Epoch: 1932; square error: 2.2091
Epoch: 1933; square error: 2.2091
Epoch: 1934; square error: 2.2091
Epoch: 1935; square error: 2.2091
Epoch: 1936; square error: 2.2091
Epoch: 1937; square error: 2.2091
Epoch: 1938; square error: 2.2091
Epoch: 1939; square error: 2.2091
Epoch: 1940; square error: 2.2091
Epoch: 1941; s

Epoch: 2213; square error: 2.2091
Epoch: 2214; square error: 2.2091
Epoch: 2215; square error: 2.2091
Epoch: 2216; square error: 2.2091
Epoch: 2217; square error: 2.2091
Epoch: 2218; square error: 2.2091
Epoch: 2219; square error: 2.2091
Epoch: 2220; square error: 2.2091
Epoch: 2221; square error: 2.2091
Epoch: 2222; square error: 2.2091
Epoch: 2223; square error: 2.2091
Epoch: 2224; square error: 2.2091
Epoch: 2225; square error: 2.2091
Epoch: 2226; square error: 2.2091
Epoch: 2227; square error: 2.2091
Epoch: 2228; square error: 2.2091
Epoch: 2229; square error: 2.2091
Epoch: 2230; square error: 2.2091
Epoch: 2231; square error: 2.2091
Epoch: 2232; square error: 2.2091
Epoch: 2233; square error: 2.2091
Epoch: 2234; square error: 2.2091
Epoch: 2235; square error: 2.2091
Epoch: 2236; square error: 2.2091
Epoch: 2237; square error: 2.2091
Epoch: 2238; square error: 2.2091
Epoch: 2239; square error: 2.2091
Epoch: 2240; square error: 2.2091
Epoch: 2241; square error: 2.2091
Epoch: 2242; s

Epoch: 2627; square error: 2.2091
Epoch: 2628; square error: 2.2091
Epoch: 2629; square error: 2.2091
Epoch: 2630; square error: 2.2091
Epoch: 2631; square error: 2.2091
Epoch: 2632; square error: 2.2091
Epoch: 2633; square error: 2.2091
Epoch: 2634; square error: 2.2091
Epoch: 2635; square error: 2.2091
Epoch: 2636; square error: 2.2091
Epoch: 2637; square error: 2.2091
Epoch: 2638; square error: 2.2091
Epoch: 2639; square error: 2.2091
Epoch: 2640; square error: 2.2091
Epoch: 2641; square error: 2.2091
Epoch: 2642; square error: 2.2091
Epoch: 2643; square error: 2.2091
Epoch: 2644; square error: 2.2091
Epoch: 2645; square error: 2.2091
Epoch: 2646; square error: 2.2091
Epoch: 2647; square error: 2.2091
Epoch: 2648; square error: 2.2091
Epoch: 2649; square error: 2.2091
Epoch: 2650; square error: 2.2091
Epoch: 2651; square error: 2.2091
Epoch: 2652; square error: 2.2091
Epoch: 2653; square error: 2.2091
Epoch: 2654; square error: 2.2091
Epoch: 2655; square error: 2.2091
Epoch: 2656; s

Epoch: 2910; square error: 2.2091
Epoch: 2911; square error: 2.2091
Epoch: 2912; square error: 2.2091
Epoch: 2913; square error: 2.2091
Epoch: 2914; square error: 2.2091
Epoch: 2915; square error: 2.2091
Epoch: 2916; square error: 2.2091
Epoch: 2917; square error: 2.2091
Epoch: 2918; square error: 2.2091
Epoch: 2919; square error: 2.2091
Epoch: 2920; square error: 2.2091
Epoch: 2921; square error: 2.2091
Epoch: 2922; square error: 2.2091
Epoch: 2923; square error: 2.2091
Epoch: 2924; square error: 2.2091
Epoch: 2925; square error: 2.2091
Epoch: 2926; square error: 2.2091
Epoch: 2927; square error: 2.2091
Epoch: 2928; square error: 2.2091
Epoch: 2929; square error: 2.2091
Epoch: 2930; square error: 2.2091
Epoch: 2931; square error: 2.2091
Epoch: 2932; square error: 2.2091
Epoch: 2933; square error: 2.2091
Epoch: 2934; square error: 2.2091
Epoch: 2935; square error: 2.2091
Epoch: 2936; square error: 2.2091
Epoch: 2937; square error: 2.2091
Epoch: 2938; square error: 2.2091
Epoch: 2939; s

Epoch: 3387; square error: 2.2091
Epoch: 3388; square error: 2.2091
Epoch: 3389; square error: 2.2091
Epoch: 3390; square error: 2.2091
Epoch: 3391; square error: 2.2091
Epoch: 3392; square error: 2.2091
Epoch: 3393; square error: 2.2091
Epoch: 3394; square error: 2.2091
Epoch: 3395; square error: 2.2091
Epoch: 3396; square error: 2.2091
Epoch: 3397; square error: 2.2091
Epoch: 3398; square error: 2.2091
Epoch: 3399; square error: 2.2091
Epoch: 3400; square error: 2.2091
Epoch: 3401; square error: 2.2091
Epoch: 3402; square error: 2.2091
Epoch: 3403; square error: 2.2091
Epoch: 3404; square error: 2.2091
Epoch: 3405; square error: 2.2091
Epoch: 3406; square error: 2.2091
Epoch: 3407; square error: 2.2091
Epoch: 3408; square error: 2.2091
Epoch: 3409; square error: 2.2091
Epoch: 3410; square error: 2.2091
Epoch: 3411; square error: 2.2091
Epoch: 3412; square error: 2.2091
Epoch: 3413; square error: 2.2091
Epoch: 3414; square error: 2.2091
Epoch: 3415; square error: 2.2091
Epoch: 3416; s

Epoch: 3753; square error: 2.2091
Epoch: 3754; square error: 2.2091
Epoch: 3755; square error: 2.2091
Epoch: 3756; square error: 2.2091
Epoch: 3757; square error: 2.2091
Epoch: 3758; square error: 2.2091
Epoch: 3759; square error: 2.2091
Epoch: 3760; square error: 2.2091
Epoch: 3761; square error: 2.2091
Epoch: 3762; square error: 2.2091
Epoch: 3763; square error: 2.2091
Epoch: 3764; square error: 2.2091
Epoch: 3765; square error: 2.2091
Epoch: 3766; square error: 2.2091
Epoch: 3767; square error: 2.2091
Epoch: 3768; square error: 2.2091
Epoch: 3769; square error: 2.2091
Epoch: 3770; square error: 2.2091
Epoch: 3771; square error: 2.2091
Epoch: 3772; square error: 2.2091
Epoch: 3773; square error: 2.2091
Epoch: 3774; square error: 2.2091
Epoch: 3775; square error: 2.2091
Epoch: 3776; square error: 2.2091
Epoch: 3777; square error: 2.2091
Epoch: 3778; square error: 2.2091
Epoch: 3779; square error: 2.2091
Epoch: 3780; square error: 2.2091
Epoch: 3781; square error: 2.2091
Epoch: 3782; s

Epoch: 4202; square error: 2.2091
Epoch: 4203; square error: 2.2091
Epoch: 4204; square error: 2.2091
Epoch: 4205; square error: 2.2091
Epoch: 4206; square error: 2.2091
Epoch: 4207; square error: 2.2091
Epoch: 4208; square error: 2.2091
Epoch: 4209; square error: 2.2091
Epoch: 4210; square error: 2.2091
Epoch: 4211; square error: 2.2091
Epoch: 4212; square error: 2.2091
Epoch: 4213; square error: 2.2091
Epoch: 4214; square error: 2.2091
Epoch: 4215; square error: 2.2091
Epoch: 4216; square error: 2.2091
Epoch: 4217; square error: 2.2091
Epoch: 4218; square error: 2.2091
Epoch: 4219; square error: 2.2091
Epoch: 4220; square error: 2.2091
Epoch: 4221; square error: 2.2091
Epoch: 4222; square error: 2.2091
Epoch: 4223; square error: 2.2091
Epoch: 4224; square error: 2.2091
Epoch: 4225; square error: 2.2091
Epoch: 4226; square error: 2.2091
Epoch: 4227; square error: 2.2091
Epoch: 4228; square error: 2.2091
Epoch: 4229; square error: 2.2091
Epoch: 4230; square error: 2.2091
Epoch: 4231; s

Epoch: 4698; square error: 2.2091
Epoch: 4699; square error: 2.2091
Epoch: 4700; square error: 2.2091
Epoch: 4701; square error: 2.2091
Epoch: 4702; square error: 2.2091
Epoch: 4703; square error: 2.2091
Epoch: 4704; square error: 2.2091
Epoch: 4705; square error: 2.2091
Epoch: 4706; square error: 2.2091
Epoch: 4707; square error: 2.2091
Epoch: 4708; square error: 2.2091
Epoch: 4709; square error: 2.2091
Epoch: 4710; square error: 2.2091
Epoch: 4711; square error: 2.2091
Epoch: 4712; square error: 2.2091
Epoch: 4713; square error: 2.2091
Epoch: 4714; square error: 2.2091
Epoch: 4715; square error: 2.2091
Epoch: 4716; square error: 2.2091
Epoch: 4717; square error: 2.2091
Epoch: 4718; square error: 2.2091
Epoch: 4719; square error: 2.2091
Epoch: 4720; square error: 2.2091
Epoch: 4721; square error: 2.2091
Epoch: 4722; square error: 2.2091
Epoch: 4723; square error: 2.2091
Epoch: 4724; square error: 2.2091
Epoch: 4725; square error: 2.2091
Epoch: 4726; square error: 2.2091
Epoch: 4727; s

In [16]:
print(model.predict(X))
print(model.stop_epoch)
print(model.w01)
print(model.w12)

[[-0.00550361]
 [-0.00550361]
 [-0.00550361]
 [-0.00550361]]
5000
[[ 9.52308855e-18 -2.70792330e-17  9.87435534e-18 -2.40034734e-17]
 [ 1.25241666e-16  1.77769034e-17 -1.25571908e-16  1.27157907e-17]
 [ 2.92202425e-17  1.60275307e-17  5.13867224e-18  1.87554779e-17]]
[[-1.10073238e-02]
 [ 1.20497059e-16]
 [-1.43316598e-18]
 [-1.24135541e-16]
 [-1.41490788e-18]]


In [17]:
# randomize the weights with zeta
model.train(X, Y, epochs=-1, input_weights=False)

Epoch: 1; square error: 2.5084
Epoch: 2; square error: 2.4694
Epoch: 3; square error: 2.4400
Epoch: 4; square error: 2.4176
Epoch: 5; square error: 2.4000
Epoch: 6; square error: 2.3857
Epoch: 7; square error: 2.3737
Epoch: 8; square error: 2.3634
Epoch: 9; square error: 2.3542
Epoch: 10; square error: 2.3459
Epoch: 11; square error: 2.3380
Epoch: 12; square error: 2.3305
Epoch: 13; square error: 2.3230
Epoch: 14; square error: 2.3155
Epoch: 15; square error: 2.3078
Epoch: 16; square error: 2.2997
Epoch: 17; square error: 2.2910
Epoch: 18; square error: 2.2817
Epoch: 19; square error: 2.2714
Epoch: 20; square error: 2.2600
Epoch: 21; square error: 2.2472
Epoch: 22; square error: 2.2329
Epoch: 23; square error: 2.2166
Epoch: 24; square error: 2.1982
Epoch: 25; square error: 2.1772
Epoch: 26; square error: 2.1532
Epoch: 27; square error: 2.1258
Epoch: 28; square error: 2.0946
Epoch: 29; square error: 2.0591
Epoch: 30; square error: 2.0185
Epoch: 31; square error: 1.9725
Epoch: 32; square

In [18]:
print(model.predict(X))
print(model.stop_epoch)
print(model.w01)
print(model.w12)

[[-0.93745399]
 [ 0.82616531]
 [ 0.86694782]
 [-0.84106674]]
66
[[ 2.64155526  2.20159195 -1.44087557 -0.25354822]
 [ 2.40605244 -1.59186836  2.39751554 -0.4578249 ]
 [-2.82897635 -1.85596483 -1.46726097 -0.22597629]]
[[ 1.12257245]
 [-3.40818156]
 [ 2.24843296]
 [ 3.13365349]
 [-0.48253575]]
